# Site settings
title: "Debashish Reang"
email: "reang.bade@gmail.com"
description: "I'm Debashish Reang, a third-year undergrad at the Indian Institute of Technology Kanpur. I grew up chasing chickens in a small village in India, aspiring to be a pilot looking at the aeroplanes flying over me. I aspire to be a writer, computer scientist, politician, comic artist and many more."
baseurl: ""
url: "https://reangdeba.xyz"
twitter_username: reangdeba
github_username:  reangdeba
author: Debashish Reang
title_image: "/assets/images/dp_alt.jpg"

# Build settings
markdown: kramdown
permalink: pretty
future: true

# disqus and google_analytics
google_analytics: UA-141493078-1
disqus_shortname: reangdeba

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-last-modified-at
