# Site settings
title: reang's blog
email: 
description: "The life and thoughts of Reang."
baseurl: ""
url: "https://reangdeba.github.io"
twitter_username: reangdeba
github_username:  reangdeba

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
