# Site settings
title: "Debashish Reang"
email: "reang.bade@gmail.com"
description: "I am a third year undergraduate student at IIT Kanpur majoring in Electrical Engineering. I am broadly interested in Computer Vision and Biology. Before coming to Kanpur, I was at NPS International School Guwahati where I titrated chemicals, multiplied lots of matrices, and wrote the JEE Advanced exam! Even before that, I spent the first 16 years of my life living in a small state known as Tripura, in the North Eastern part of India."
baseurl: ""
url: "https://reangdeba.xyz"
twitter_username: reangdeba
github_username:  reangdeba
author: Debashish Reang

# Build settings
markdown: kramdown
permalink: pretty

# disqus and google_analytics
google_analytics: UA-141493078-1
disqus_shortname: reangdeba

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jemoji
  - jekyll-feed
