# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Debashish Reang
email: reang.bade@gmail.com
description: "Hi! I am Debashish Reang, a sophomore at the Indian Institute
of Technology Kanpur. Deeply interested in Computer Science and Education, I
aspire to get a PhD in Computational Biology and serve as a member of faculty."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://reangdeba.github.io" # the base hostname & protocol for your site, e.g. https://example.com
facebook_username: imreang
github_username:  reangdeba

author: Debashish Reang
twitter:
  username: reangdeba
  card: "Debashish Reang, fondly called Reang is a sophomore at the Indian Institute
  of Technology Kanpur. Deeply interested in Computer Science and Education, he
  aspires to get a PhD in Computational Biology and serve as a member of faculty."

social:
  name: Debashish Reang
  links:
    - https://twitter.com/reangdeba
    - https://www.facebook.com/imreang
    - https://www.linkedin.com/in/reangdeba
    - https://github.com/reangdeba

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

share: true # Turn on twitter and facebook share buttons
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
